server:
  port: 18811
spring:
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - file:${upload-path}
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  banner:
    location: https://img.rrztech.com/banner.txt
  datasource:
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 30
      minimum-idle: 20
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 900000
  mail:
    host: smtp.163.com
    username: weiqiming0608@163.com
    password: QDMGQUARRHKYKWXZ
    port: 25
    default-encoding: utf-8
  jackson:
    serialization.FAIL_ON_EMPTY_BEANS: false
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.share.api.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false