logging:
  level:
    "com.luban.api.lubanapi": debug
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${H5_DB_URL:192.168.1.110:3306}/luban?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${H5_DB_USERNAME:root}
    password: ${H5_DB_PASSWORD:root}
  devtools:
    add-properties: true
upload-path: ${UPLOAD_PATH:D:/h5_file/}