logging:
  level:
    "com.share.api": debug
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${H5_DB_URL:192.168.1.110:3306}/luban?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${H5_DB_USERNAME:root}
    password: ${H5_DB_PASSWORD:root}
  devtools:
    add-properties: true
  freemarker:
    template-loader-path: classpath:/templates
upload-path: ${UPLOAD_PATH:images/}
mail:
  fromMail:
    addr: weiqiming0608@163.com
  verificationCodeTemplate: verificationCodeTemplate.ftl
verificationCode:
  timeout: 30
  maxCount: 10